--- a/Makefile	2015-04-15 13:00:25.000000000 +0300
+++ b/Makefile	2015-09-30 00:39:11.609429878 +0300
@@ -38,26 +38,26 @@
 
 
 
-CC = gcc 
+# CC = gcc 
 
-LDFLAGS = -lssl -lcrypto -lpthread -ldl -D_REENTRANT
+LDFLAGS += -lssl -lcrypto -lpthread -ldl -D_REENTRANT
 
 #Elena Agostini: libnl
 LDFLAGS += -lnl-genl-3 -lnl-3
-LIB_PATH = /usr/local/lib
-INC_PATH = /usr/include/libnl3
+# LIB_PATH = /usr/local/lib
+# INC_PATH = /usr/include/libnl3
  
 #LDFLAGS = /usr/lib/libefence.a ./static/libssl.a ./static/libcrypto.a -lpthread -ldl -D_REENTRANT
 #LDFLAGS = ./static/libssl.a ./static/libcrypto.a -lpthread -ldl -D_REENTRANT
 
-CFLAGS =  -Wall -g -O0 -D_REENTRANT  
+CFLAGS +=  -Wall -g -O0 -D_REENTRANT  
 #CFLAGS += -DCW_NO_DTLS -DCW_NO_DTLSCWParseConfigurationUpdateRequest
 CFLAGS += -DSPLIT_MAC
 
 #DTLS Data Channel
 CFLAGS += -DCW_DTLS_DATA_CHANNEL
 
-OPENSSL_INCLUDE = -I./include/  #Openssl include files
+# OPENSSL_INCLUDE = -I./include/  #Openssl include files
 
 # Memory leak
 #LDFLAGS += ../dmalloc-5.5.0/libdmallocth.a
@@ -73,8 +73,8 @@
 #OpenSSL inc files path
 #CFLAGS += $(OPENSSL_INCLUDE)  
 
-CFLAGS += -I/usr/include/libnl3
-CFLAGS += -I./HostapdHeaders/utils/
+# CFLAGS += -I/usr/include/libnl3
+# CFLAGS += -I./HostapdHeaders/utils/
 RM = /bin/rm -f 
 
 # list of generated object files for AC. 
