#!/bin/sh
# This script is executed as part of the hotplug event with
# HOTPLUG_TYPE=iface, triggered by various scripts when an interface
# is configured (ACTION=ifup) or deconfigured (ACTION=ifdown).  The
# interface is available as INTERFACE, the real device as DEVICE.

[ "$DEVICE" == "lo" ] && exit 0
[ "$INTERFACE" == "gsm" ] || exit 0
. /lib/functions.sh
. /lib/firewall/core.sh

# fw_init
# fw_is_loaded || exit 0

case "$ACTION" in
	ifup)
		# echo "$INTERFACE" "$DEVICE" >> /tmp/tests
		/usr/bin/interfacewatchdog $INTERFACE 2>/dev/null >/dev/null &
		
	;;
	ifdown)
		# echo "$INTERFACE" "$DEVICE" >> /tmp/tests
		ifup $INTERFACE
	;;
esac
