#!/bin/sh
self=${0##*/}
interface=$1
echo $self $interface
. /lib/functions/network.sh
count=0
logger -t $self "Start watching $interface"
while [ $count -le 3 ] ; do 
	sleep 5
	network_get_dnsserver tmpdns $interface
	[ "$tmpdns" ] || exit
	let count++
	for dns in $tmpdns ; do
		ping -q -c1 $dns && count=0
	done
logger -t $self "$interface : $count"
done
logger -t $self "ifdown $interface"
ifdown $interface &
exit 0

